version: '3.3'

services:
  app:
    image: spliit2:latest
    ports:
      - 13000:3000
    env_file:
      - container.env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:latest
    ports:
      - 15432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
