version: '3.3'

services:
  frontend:
    image: split/frontend:latest
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/build:/app/build
    ports:
      - "9903:3000"
    env_file:
      - ./frontend/container.env
    depends_on:
      - dbfrontend
    restart: always
  dbfrontend:
    image: postgres:latest
    ports:
      - 15432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./frontend/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
  nginx:
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

    # lol apparently not allowed so soft dependency it is
    # depends-on:
    #  - frontend
