version: '3.3'

services:
  db:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - database:/var/lib/postgresql/data
    restart: always
  backend:
    image: split/backend:latest
    build: ./backend
    volumes:
      - ./backend/src:/app/src
    ports:
      - "9901:80"
    depends_on:
      - db
    restart: always
  nginx:
    image: split/nginx:latest
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/static:/frontend/static
      - ./frontend/build:/frontend/build
    depends_on:
      - backend
    restart: always
  websockets:
    image: split/websockets:latest
    build: ./websockets
    ports:
      - "9902:80"
    restart: always
volumes:
  database:
