version: '3.3'

services:
  frontend:
    image: split/frontend:latest
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/build:/app/build
    ports:
      - "9903:3000"
    restart: always
  nginx:
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

    # lol apparently not allowed so soft dependency it is
    # depends-on:
    #  - frontend
