# Generated by Django 4.0.4 on 2024-12-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='venmo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
